#
# updated by ...: Loreto Notarantonio
# Date .........: 05-05-2024 08.45.12
#

#########################################################
# -       MqttMonitor config data
#########################################################


main:
    still_alive_interval_hours:
            # - 1
            # - 7
            # - 13
            # - 19
            - 8
    send_status_hours:
            - 21
            # - 21

    mqtt_broker_name: LnMqtt



system_variables: !include system_variables.lnk.yaml#system_envars


sqlite:
    mqtt:
        !include mqtt_devices_DBase.lnk.yaml

