#
# updated by ...: Loreto Notarantonio
# Date .........: 08-07-2024 17.14.33
#

#########################################################
# -       MqttMonitor config data
#########################################################


main:
    still_alive_interval_hours:
            # - 1
            # - 7
            # - 13
            # - 19
            - 8
    send_status_hours:
            - 21
            # - 21

    mqtt_broker_name: LnMqtt



system_variables: !include system_variables.lnk.yaml#system_envars


# sqlite:
#     !include devices_DBase.lnk.yaml



sqlite:
    !include devices_DBase.lnk.yaml
    # !include "${HOME}/lnProfile/devicesDB/${DB_VERSION_DIR}/conf/devices_DBTables.yaml"
