#
# updated by ...: Loreto Notarantonio
# Date .........: 04-05-2024 08.20.51
#

#########################################################
# -       MqttMonitor config data
#########################################################


main:
    still_alive_interval_hours:
            # - 1
            # - 7
            # - 13
            # - 19
            - 8
    send_status_hours:
            - 21
            # - 21

    mqtt_broker_name: LnMqtt



system_variables: !include system_variables.lnk.yaml#system_envars


sqlite:

    !include devices_DBTables.lnk.yaml
    # tables: !include devices_DBase.lnk.yaml#tables

    # db_filepath:    will be filled by __main__ program

