#
# updated by ...: Loreto Notarantonio
# Date .........: 03-05-2024 13.41.32
#

#########################################################
# -       MqttMonitor config data
#########################################################


main:
    still_alive_interval_hours:
            # - 1
            # - 7
            # - 13
            # - 19
            - 8
    send_status_hours:
            - 21
            # - 21

    mqtt_broker_name: LnMqtt



system_variables: !include system_variables.lnk.yaml#system_envars


sqlite:
    tables: !include devices_DBase.lnk.yaml#tables

    db_filepath:    will be filled by __main__ program

