#
# updated by ...: Loreto Notarantonio
# Date .........: 19-02-2024 17.13.15
#

#########################################################
# -       MqttMonitor config data
#########################################################


main:
    still_alive_interval_hours:
            # - 1
            # - 7
            # - 13
            # - 19
            - 8
    send_status_hours:
            - 21
            # - 21


system_variables: !include conf/ln_system_variables.lnk.yaml#system_envars



devices:
    bots:       !include "conf/telegramBots.lnk.yaml#bots"
    broker:     !include "conf/Mqtt_Brokers.lnk.yaml#brokers.lnmqtt"
    data:       !include "conf/devicesDB_list.lnk.csv#name"
    extra_data: !include_merge [
                    "conf/Computers.lnk.yaml#raspberry",
                    "conf/Computers.lnk.yaml#pc",
                    "conf/Tasmota.lnk.yaml#tasmota",
                    "conf/telegramApplications.lnk.yaml#application_groups",
                    "conf/telegramChannels.lnk.yaml#channels",
                ]


